// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK9xTC_yYPKINyjYvgQKTpYmyoXXzUktc',
    appId: '1:241627293072:web:043818b3e75b6ad6157f15',
    messagingSenderId: '241627293072',
    projectId: 'servicioselalto',
    authDomain: 'servicioselalto.firebaseapp.com',
    storageBucket: 'servicioselalto.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwIIdDbWexXxJTPdmhunH_LYSrcmTwhJw',
    appId: '1:241627293072:android:2bea5ed3fa505f33157f15',
    messagingSenderId: '241627293072',
    projectId: 'servicioselalto',
    storageBucket: 'servicioselalto.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5IGHRYxS-EJMlPI6J7Hef9ZRbo8A3yhA',
    appId: '1:241627293072:ios:12566ab7c00bdd13157f15',
    messagingSenderId: '241627293072',
    projectId: 'servicioselalto',
    storageBucket: 'servicioselalto.firebasestorage.app',
    androidClientId: '241627293072-1e2cjrni7sm5nnkp1sk002qjumr9efu1.apps.googleusercontent.com',
    iosClientId: '241627293072-0a2oon8e5174leslqk20ase8e3lat98c.apps.googleusercontent.com',
    iosBundleId: 'com.example.sistemaServicios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5IGHRYxS-EJMlPI6J7Hef9ZRbo8A3yhA',
    appId: '1:241627293072:ios:12566ab7c00bdd13157f15',
    messagingSenderId: '241627293072',
    projectId: 'servicioselalto',
    storageBucket: 'servicioselalto.firebasestorage.app',
    androidClientId: '241627293072-1e2cjrni7sm5nnkp1sk002qjumr9efu1.apps.googleusercontent.com',
    iosClientId: '241627293072-0a2oon8e5174leslqk20ase8e3lat98c.apps.googleusercontent.com',
    iosBundleId: 'com.example.sistemaServicios',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK9xTC_yYPKINyjYvgQKTpYmyoXXzUktc',
    appId: '1:241627293072:web:24a5f3f3170c444d157f15',
    messagingSenderId: '241627293072',
    projectId: 'servicioselalto',
    authDomain: 'servicioselalto.firebaseapp.com',
    storageBucket: 'servicioselalto.firebasestorage.app',
  );

}